### ISSUE TITLE
Independencies installation failed

### ISSUE THREAD

**Issue by HansonYip** [kartotherian/kartotherian#108]
## Environment
* Node version: v8.16.0
* Lerna version: v3.14.1
* OS: Mac 10.14.4
* Mapnik version: 3.0.22 (use `brew install mapnik` to install)

To install the dependencies for all modules, I run the following from the project root, but it has something wrong.
```bash
lerna bootstrap --hoist --nohoist mapnik --nohoist libxmljs
lerna notice cli v3.14.1
lerna info versioning independent
lerna ERR! EWORKSPACES --hoist is not supported with --npm-client=yarn, use yarn workspaces instead
lerna ERR! EWORKSPACES A guide is available at https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/
```

And I try to run another command `yarn install` from the project root, but it still does not work.
```bash
$ yarn install                         yarn install v1.16.0
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
warning clarinet@0.11.0: The engine "firefox" appears to be invalid.
warning clarinet@0.11.0: The engine "chrome" appears to be invalid.
[3/4] 🔗  Linking dependencies...
warning " > @kartotherian/abaculus@3.0.1" has unmet peer dependency "mapnik@~3.7.0".
warning " > @kartotherian/tilelive-tmsource@1.0.0" has unmet peer dependency "mapnik@^3.7.0".
warning " > @kartotherian/tilelive-vector@4.0.1" has unmet peer dependency "mapnik@~3.7.0".
warning "workspace-aggregator-1506f268-a74c-4387-90bc-dd4623300415 > @kartotherian/babel > eslint-config-airbnb-base@12.1.0" has unmet peer dependency "eslint@^4.9.0".
warning "workspace-aggregator-1506f268-a74c-4387-90bc-dd4623300415 > @kartotherian/babel > eslint-config-airbnb-base@12.1.0" has unmet peer dependency "eslint-plugin-import@^2.7.0".
warning "workspace-aggregator-1506f268-a74c-4387-90bc-dd4623300415 > kartotherian > tilelive-tmstyle@0.8.0" has unmet peer dependency "@mapbox/tilelive-vector@>=2.0.0".
warning "workspace-aggregator-1506f268-a74c-4387-90bc-dd4623300415 > @kartotherian/server > eslint-plugin-import@2.16.0" has unmet peer dependency "eslint@2.x - 5.x".
[4/4] 🔨  Building fresh packages...
[7/10] ⠠ heapdump
[2/10] ⠠ mapnik
[3/10] ⠠ mapnik
[6/10] ⠠ dtrace-provider
error ./kartotherian/node_modules/canvas: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: ./kartotherian/node_modules/canvas
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@8.16.0 | darwin | x64
gyp http GET https://nodejs.org/download/release/v8.16.0/node-v8.16.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v8.16.0/node-v8.16.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v8.16.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v8.16.0/SHASUMS256.txt
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ './kartotherian/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   './kartotherian/node_modules/canvas/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   './kartotherian/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '~/.node-gyp/8.16.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=~/.node-gyp/8.16.0',
gyp info spawn args   '-Dnode_gyp_dir=./kartotherian/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=~/.node-gyp/8.16.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=./kartotherian/node_modules/canvas',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
Package libffi was not found in the pkg-config search path.
Perhaps you should add the directory containing `libffi.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libffi', required by 'gobject-2.0', not found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (./kartotherian/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 18.5.0
gyp ERR! command "~/.nvm/versions/node/v8.16.0/bin/node" "./kartotherian/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd ./kartotherian/node_modules/canvas
```

**Comment by MaxSem** [comment]
Does it also fail with NPM?

**Comment by HansonYip** [comment]
@MaxSem I fix the problem by setting env `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig`. Thank you.
