### ISSUE TITLE
Issues with yarn

### ISSUE THREAD

**Issue by Phyks** [kartotherian/kartotherian#83]
Hi,

I tried to use `yarn` to install JS deps and run kartotherian. I am running node v8.14.0, yarn v1.12.3 on Ubuntu 18.04 LTS. Everything runs fine when using `npm`.

When running `yarn install`, no error is shown. However, when starting kartotherian (with the config.external.yaml file), I get the following trace:

```
$ yarn run start
yarn run v1.12.3
$ service-runner
[2019-01-04T13:36:58.177Z]  INFO: kartotherian/3275 on ubuntu-bionic: Loading variables from the config file (levelPath=info)
[2019-01-04T13:36:58.184Z]  INFO: kartotherian/3275 on ubuntu-bionic: Loading sources from /tmp/kartotherian/sources.external.yaml (levelPath=info)
[2019-01-04T13:36:59.026Z] FATAL: kartotherian/3275 on ubuntu-bionic: /tmp/kartotherian/node_modules/@mapbox/blend/node_modules/mapnik/lib/binding/mapnik.node: undefined symbol: _ZN6mapnik19MAPNIK_LONGLAT_PROJE
    Error: /tmp/kartotherian/node_modules/@mapbox/blend/node_modules/mapnik/lib/binding/mapnik.node: undefined symbol: _ZN6mapnik19MAPNIK_LONGLAT_PROJE
        at Object.Module._extensions..node (module.js:682:18)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/tmp/kartotherian/node_modules/@mapbox/blend/node_modules/mapnik/lib/mapnik.js:31:15)
        at Module._compile (module.js:653:30)
        at Object.Module._extensions..js (module.js:664:10)
        at Module.load (module.js:566:32)
        at tryModuleLoad (module.js:506:12)
        at Function.Module._load (module.js:498:3)
        at Module.require (module.js:597:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (/tmp/kartotherian/node_modules/@mapbox/blend/index.js:1:76)
        at Module._compile (module.js:653:30)
error Command failed with exit code 1.
```

It looks like a `mapnik` build issue with yarn.

Best,

**Comment by thesocialdev** [comment]
@Phyks what is the version of mapnik installed?

**Comment by Phyks** [comment]
I got this while using `3.0.19+ds-1` from Ubuntu bionic repo.

**Comment by thesocialdev** [comment]
We current run 3.0.20 after the following task https://phabricator.wikimedia.org/T188674

I suggest you to upgrade mapnik version, you can try the wikimedia backpoted version of mapnik 3.0.20, see https://github.com/mateusbs17/gisdock/blob/master/kartotherian/Dockerfile#L11

If that's not the case you might also consider that kartotherian is not able to run with the latest version of node v10.x.

Let me know if the problem persists

**Comment by Phyks** [comment]
Thanks for the details on this! What is puzzling me is that it works fine with `npm` and this Mapnik + Node version, but not with `yarn`. Not sure why, but this is likely to be an issue from `node-mapnik` rather than kartotherian actually.

May I suggest to update https://github.com/kartotherian/kartotherian#install-other-software-dependencies to install the backported Mapnik version instead?

Thanks!
Best,

**Comment by thesocialdev** [comment]
> May I suggest to update https://github.com/kartotherian/kartotherian#install-other-software-dependencies to install the backported Mapnik version instead?

Nice find! Thanks for the suggestion.
