### ISSUE TITLE
tileCodec tests fail with "Error: Unexpected layer tag #0"

### ISSUE THREAD

**Issue by mooeypoo** [kartotherian/kartotherian#92]
After 'fixing' (and getting rid of) the test for content encoding, the splicerTest unit tests now fail on `Error: Unexpected layer tag #0`

This is coming from [splicerTest.js line #59](https://github.com/kartotherian/babel/blob/master/test/splicerTest.js#L58) where it seems something inside the data sent to the `tileCodec.decodeTile(result.data);` leads to a layer tag 0, which is unexpected (see https://github.com/kartotherian/babel/blob/master/lib/tileCodec.js#L60 ) 

The full stack trace for one of the failures:

```
9) Tag recombination pick missing:
     Error: Unexpected layer tag #0
      at Tile.Layer._readField (lib/tileCodec.js:123:24)
      at Object.readFields (node_modules/pbf/index.js:39:13)
      at Object.Tile.Layer.read (lib/tileCodec.js:108:16)
      at Tile._readField (lib/tileCodec.js:27:36)
      at Object.readFields (node_modules/pbf/index.js:39:13)
      at Object.Tile.read (lib/tileCodec.js:22:16)
      at Object.decodeTile (lib/tileCodec.js:7:21)
      at babel.then.then.result (test/splicerTest.js:59:37)
      at Gzip.onEnd (zlib.js:227:5)
      at endReadableNT (_stream_readable.js:974:12)
      at _combinedTickCallback (internal/process/next_tick.js:80:11)
      at process._tickCallback (internal/process/next_tick.js:104:9)
  From previous event:
      at test (test/splicerTest.js:50:11)
      at Context.it (test/splicerTest.js:257:30)
```

I can't make sense of the data or why and how the tag is sent incorrectly. Is this a known bug? Is this indicating a deeper issue with the tile codec code? It's hard to test since babel isn't really used yet, as far as I can see, so I can't tell if the test itself is sending bad data (the code is correct) or if the test is good but its failure indicates something is wrong with the tile codec reading method (the code is broken)

**Comment by nyurik** [comment]
thx @mooeypoo , I'll take a look.
